# https://github.com/marketplace/actions/image-optimizer-action
name: Compress Images
on:
  workflow_dispatch:
  #schedule: [{cron: "0 0 * * *"}]

jobs:
  compress:
    name: Compress Images
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Exclude metrics SVGs
        run: |
          mkdir -p "$RUNNER_TEMP/excluded"
          [[ -f metrics.classic.svg ]] && mv metrics.classic.svg "$RUNNER_TEMP/excluded/" || :
          [[ -f metrics.svg ]] && mv metrics.svg "$RUNNER_TEMP/excluded/" || :

      - name: Compress Images
        id: compress-images
        uses: stellasoftio/image-optimizer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          export-webp: true
          export-avif: false
          compress-png: true
          compress-svg: true
          compress-jpg: true
          compress-webp: true
          compress-avif: true
          replace-original-after-export-webp: true

      - name: Restore excluded files
        run: |
          [[ -f "$RUNNER_TEMP/excluded/metrics.classic.svg" ]] && mv "$RUNNER_TEMP/excluded/metrics.classic.svg" . || :
          [[ -f "$RUNNER_TEMP/excluded/metrics.svg" ]] && mv "$RUNNER_TEMP/excluded/metrics.svg" . || :

      - name: Create Pull Request if Images Were Compressed
        if: ${{ steps.compress-images.outputs.markdown_report != '' }}
        uses: peter-evans/create-pull-request@v5
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.compress-images.outputs.markdown_report }}
