name: Update Dynamic Repos and Cool Animations

on:
  schedule:
    - cron: "0 4 * * *" # Once daily
  workflow_dispatch:

jobs:
  update-profile-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate profile details
        uses: gayanvoice/github-profile-activity-generator@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_REPOS: 6
          COMMIT_MESSAGE: "chore: update dynamic repo and activity lists"
          REPOSITORY: 'Ven0m0/Ven0m0' # Must match your profile repo

      - name: Push README
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README.md
          git diff --cached --quiet || git commit -m "chore: update animated/dynamic repos"
          git push
